version: '3'

services:
  springboot:
    image: prasad473/spring-boot-mongo:latest
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    ports:
      - 8080:8080
    networks:
    - springappnetwork  
    

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    external: true
    
networks:
  springappnetwork:
    external: true
