version: "3"

services:
  springboot:
    environment:
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=dev@123
  mongo:
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=dev@123
